
name: CI

on:
  schedule:
    - cron: "* */2 * * *"
  

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SECRET_REPOSITORY }}
      - name: general
        run: |
          O_DATE=$(data +%s)
          git checkout -b feat/${O_DATE}
          git push -u origin feat/${O_DATE}

