
name: CI

on:
  schedule:
    - cron: "* */2 * * *"
  push:
    [main]
  

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_GITHUB }}
      - name: general
        run: |
          O_DATE=$(date +%s)
          git checkout -b feat/${O_DATE}
          git push -u origin feat/${O_DATE}

