
name: CI

on:
  schedule:
    - cron: "*/15 * * * *"
  

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           token: ${{ secrets.SECRET_REPOSITORY }}
      - name: configure git
        run: |
          git config user.name "JonasXPX"
          git config user.email "jonasdefarias@hotmail.com"
      - name: run my cron
        run: |
          CRON_DATA="${{ secrets.CRON_DATA }}"
          sed -i 's/\(DATA=\).*/\1${CRON_DATA}/' info.data
      - name: deploy changes
        run: |
          git add info.data
          git commit -m "Cron changes"
          git status
          git push
          
