
name: CI

on:
  push:
    branches: [main]
  schedule:
    - cron: "* */2 * * *"

  workflow_dispatch:
env:
 cron_data: ${{ vars.CRON_DATA }}
 o_date: $(date +%s)
jobs:
  build:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_GITHUB }}
      - name: prepare changes
        run: |
          git checkout -b feat/${O_DATE}
      - name: change the file
        run: |
          sed -i 's/\(DATA=\).*/\1${cron_data}/' info.data
      - name: push changes
        run: |
          git push -u origin feat/${O_DATE}

