
name: CI

on:
  push:
    branches: [main]
  schedule:
    - cron: "* */2 * * *"

  workflow_dispatch:
env:
 cron_data: ${{ vars.CRON_DATA }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_GITHUB }}
      - name: prepare changes
        run: |
          git checkout -b feat/${GITHUB_RUN_ID}
      - name: change the file
        run: |
          sed -i 's|\(DATA=\).*|\1$env:cron_data|' info.data
      - name: push changes
        run: |
          git push -u origin feat/${GITHUB_RUN_ID}

