
name: CI

on:
  push:
    branches: [main]
  schedule:
    - cron: "* */2 * * *"

  workflow_dispatch:
env:
 cron_data: ${{ vars.CRON_DATA }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_GITHUB }}
      - name: prepare changes
        run: |
          git config --global user.email "jonasdefarias@hotmail.com"
          git config --global user.name "JonasXPX"
      - name: change the file
        run: |
          INFO=$(curl -X GET "https://api.open-meteo.com/v1/forecast?latitude=-25.5962&longitude=-54.4872&hourly=temperature_2m&daily=sunrise,sunset&timezone=America%2FSao_Paulo")
          sed -i 's|\(DATA=\).*|\1${INFO}|' info.data
      - name: push changes
        run: |
          DATE_VERSION=$(date +%s)
          git add info.data && git commit -m "new changes made by action"
          git tag v1.0.$DATE_VERSION
          git push -u origin v1.0.$DATE_VERSION

