
name: CI

on:
  schedule:
    - cron: "* */2 * * *"
  

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - uses: actions/checkout@v3
      - name: general
        run: |
          echo "TEST" > file.json
  finish:
    runs-on: ubuntu-latest
    environment: local
    needs: build
    steps:
       - name: general continue
         run: |
            cat file.json
          
